theme: jekyll-theme-cayman
title: Pelatihan WebDev 2 KMTETI 2023/2024
description: Repository untuk menyimpan semua file modul, source code, dan file presentation dari kegiatan Pelatihan WebDev 2 KMTETI 2023/2024.